openapi: 3.0.3
info:
  title: Notifications API
  description: In-app notification endpoints for Evolution-Todo
  version: 1.0.0

paths:
  /api/notifications:
    get:
      summary: List notifications
      description: Get user's notifications, newest first
      tags: [Notifications]
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 50
        - name: unread_only
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Notification list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'
        '401':
          description: Unauthorized

    delete:
      summary: Clear all notifications
      description: Delete all notifications for the current user
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Notifications cleared
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  deleted_count:
                    type: integer
                    example: 15
        '401':
          description: Unauthorized

  /api/notifications/unread-count:
    get:
      summary: Get unread count
      description: Get count of unread notifications (lightweight endpoint for polling)
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 5
        '401':
          description: Unauthorized

  /api/notifications/{notification_id}/read:
    patch:
      summary: Mark notification as read
      description: Mark a single notification as read
      tags: [Notifications]
      security:
        - bearerAuth: []
      parameters:
        - name: notification_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
        '404':
          description: Notification not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    NotificationType:
      type: string
      enum:
        - TASK_DUE_SOON
        - TASK_OVERDUE
        - TASK_COMPLETED
      description: |
        - TASK_DUE_SOON: Task is due tomorrow
        - TASK_OVERDUE: Task is past due date
        - TASK_COMPLETED: Task was marked complete

    Notification:
      type: object
      required:
        - id
        - userId
        - type
        - message
        - isRead
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        userId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        taskId:
          type: string
          format: uuid
          nullable: true
          example: "789e0123-e45b-67d8-a901-234567890abc"
        type:
          $ref: '#/components/schemas/NotificationType'
        message:
          type: string
          example: "Task 'Finish report' is due tomorrow"
          maxLength: 500
        isRead:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: "2026-02-12T10:30:00Z"

    NotificationListResponse:
      type: object
      required:
        - notifications
        - total
        - unreadCount
      properties:
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        total:
          type: integer
          description: Total notifications returned
          example: 20
        unreadCount:
          type: integer
          description: Count of unread notifications
          example: 5
